sudo: required
dist: trusty
group: deprecated-2017Q4

language: go

services:
  - docker

addons:
  postgresql: "9.6"

go:
  - 1.7.6
  - 1.8.7
  - 1.9.3
  - 1.10.1

before_install:
  - ./script/check_formatting.sh
  - ./script/check_assets.sh

install:
  - make setup

script:
  - make build
  - make test
  - make test-all
  - make docker-release